name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build . -t ferdinandjrdocker/barks_meows_paradise:latest
      - name: push image to docker hub
        run: |
          docker login -u ferdinandjrdocker -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ferdinandjrdocker/barks_meows_paradise:latest